/// Flutter icons LigrettoCounterIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LigrettoCounterIcons
///      fonts:
///       - asset: fonts/LigrettoCounterIcons.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class LigrettoCounterIcons {
  LigrettoCounterIcons._();

  static const _kFontFam = 'LigrettoCounterIcons';
  static const String? _kFontPkg = null;

  static const IconData add_points =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_user =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_user =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reset =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
